(input_seqnames,) = glob_wildcards("Data/{filename}.faa") 

rule all:
    input: expand("results/{name}.mafft_aligned.fasttree_gtr.tre", name = input_seqnames), expand("results/{name}.mafft_aligned.fasttree_lg.tre", name = input_seqnames),




rule mafft:
    input: "Data/{seqname}.faa"
    output:"intermediate/{seqname}.mafft_aligned.faa"
    shell:"module load mafft && mafft {input} > {output}"



rule fasttree:
    input: "intermediate/{seqname}.{aligner}_aligned.faa"
    output: "results/{seqname}.{aligner}_aligned.fasttree_{model}.tre"
    log: "log/{seqname}.{aligner}_aligned.fasttree_{model}.log"
    shell: "module load fasttree && fasttree -{wildcards.model} -log {log} {input} > {output}" 
